# -*- coding: utf-8 -*-
"""Paginacion-Memory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPfSebIBTDWCAtt9fzGtmj5Yy3EFEtOD
"""

import pandas as pd
import sqlite3
from google.colab import drive

# ===============================
# CONFIGURACIÓN
# ===============================
RUTA_CSV = "/content/drive/MyDrive/Ayudantía Arquitectura de Computadores/memory_accesses.csv"
DB_NAME = "paging.db"

# ===============================
# SIMULACIÓN DE PAGINACIÓN (FIFO)
# ===============================
def simulate_paging(df, num_frames):
    frames = []
    page_table = {}
    log = []

    for _, row in df.iterrows():
        time = row["time"]
        pid = row["pid"]
        virtual_page = row["virtual_page"]
        page = (pid, virtual_page)

        if page in page_table:
            page_fault = 0
        else:
            page_fault = 1

            if len(frames) >= num_frames:
                removed = frames.pop(0)
                del page_table[removed]

            frames.append(page)
            page_table[page] = len(frames) - 1 ##INDICE QUE INDICA DONDE CARGO EL S.O LA PAGINA ESTA EN EL ULTIMO FRAME OCUPADO. N° frame donde estara la pagina.

        log.append({
            "time": time,
            "pid": pid,
            "virtual_page": virtual_page,
            "page_fault": page_fault,
            "frames": str(frames)
        })

    return pd.DataFrame(log)

# ===============================
# GUARDAR EN SQLITE
# ===============================
def guardar_en_sql(df):
    conn = sqlite3.connect(DB_NAME)
    df.to_sql("paging_log", conn, if_exists="replace", index=False)
    conn.close()

# ===============================
# MÉTRICAS (SQL OCULTO)
# ===============================
def mostrar_metricas():
    conn = sqlite3.connect(DB_NAME)
    cur = conn.cursor()

    print("\n📊 MÉTRICAS GENERALES\n")

    cur.execute("""
        SELECT
            COUNT(*) AS accesos,
            SUM(page_fault) AS fallos,
            ROUND(100.0 * SUM(page_fault) / COUNT(*), 2) AS tasa
        FROM paging_log
    """)
    accesos, fallos, tasa = cur.fetchone()

    print(f"Total de accesos: {accesos}")
    print(f"Page faults totales: {fallos}")
    print(f"Tasa de page faults: {tasa}%\n")

    print("📌 Page faults por proceso:\n")

    cur.execute("""
        SELECT
            pid,
            COUNT(*) AS accesos,
            SUM(page_fault) AS fallos,
            ROUND(100.0 * SUM(page_fault) / COUNT(*), 2) AS tasa
        FROM paging_log
        GROUP BY pid
    """)

    for pid, acc, fallos, tasa in cur.fetchall():
        print(f"Proceso {pid}:")
        print(f"  Accesos: {acc}")
        print(f"  Page faults: {fallos}")
        print(f"  Tasa: {tasa}%\n")

    conn.close()

# ===============================
# COMPARAR ESCENARIOS
# ===============================
def comparar_frames(df, frames_list):
    print("\n🔬 COMPARACIÓN DE ESCENARIOS\n")

    for frames in frames_list:
        df_log = simulate_paging(df, frames)
        fallos = df_log["page_fault"].sum()
        tasa = round(100 * fallos / len(df_log), 2)

        print(f"Frames = {frames}")
        print(f"  Page faults: {fallos}")
        print(f"  Tasa: {tasa}%\n")

    print("📌 Conclusión:")
    print("A mayor cantidad de frames físicos disponibles,")
    print("menor es la tasa de page faults (mejor rendimiento de memoria).")

# ===============================
# MENÚ PARA EL ALUMNO
# ===============================
def menu():
    drive.mount("/content/drive")

    df_accesses = pd.read_csv(RUTA_CSV)

    while True:
        print("\n===== SIMULADOR DE PAGINACIÓN =====")
        print("1) Ejecutar simulación")
        print("2) Ver métricas de rendimiento")
        print("3) Comparar cantidad de frames")
        print("0) Salir")

        opcion = input("Seleccione una opción: ")

        if opcion == "1":
            frames = int(input("Ingrese cantidad de frames físicos: "))
            df_log = simulate_paging(df_accesses, frames)
            guardar_en_sql(df_log)
            print("Simulación ejecutada y guardada.")

        elif opcion == "2":
            mostrar_metricas()

        elif opcion == "3":
            lista = input("Ingrese frames a comparar (ej: 1,2,4): ")
            frames_list = [int(x) for x in lista.split(",")]
            comparar_frames(df_accesses, frames_list)

        elif opcion == "0":
            print("Saliendo...")
            break

        else:
            print("Opción inválida.")

# ===============================
# EJECUCIÓN
# ===============================
menu()

from google.colab import drive
drive.mount('/content/drive')